name: 🔎 Code Safety
run-name: Running Code Safety for ${{ github.ref }} on ${{ github.event_name }} 🔎
on:
  pull_request:
    branches:
      - main
      - features/*
  workflow_call:
jobs:
  check-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-uv

      - run: uv run ruff check .


  check-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-uv

      - run: uv run ruff format --check .


  check-type-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-uv

      - run: uv run pyright


  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-uv

      - run: uv run pytest
